version: "3.9"

networks:
  my-b2b-network:

services:
  reimbursement:
    image: sfranco/com-reimbursement
    ports:
      - 8080:8080
    container_name: reimbursement
    environment:
      - EMAIL_API_URL=http://email:8081/email
    networks:
      - my-b2b-network
  email:
    image: sfranco/com-email
    container_name: email
    networks:
      - my-b2b-network