server:
  port:
    - 8082

spring:
  application:
    name: MyMediaAPI
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://34.136.139.193:5432/Requests-Database
    #    url: jdbc:postgresql://localhost:5432/Requests

    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: token_secret
  expiry: 360000

logger:
  level:
    com.example: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

#api:
#  config:
#    email-api-url: http://localhost:8081/email

api:
  config:
    email-api-url: ${EMAIL_API_URL}


